site_name: Build and Deploy Spring Petclinic Application to Amazon ECS using Terraform and AWS CodePipeline
nav:
  - 'Introduction': index.md
  - 'Modules':
    - 'Module 1 - Architecture': architecture.md
    - 'Module 2 - Prerequisites': prerequisites.md
    - 'Module 3 - Build the infrastructure': blog/ipoGCN.md
    - 'Module 4 - Deploy': infrastructure.md
    - 'Module 5 - Trigger pipeline': deploy.md
    - 'Module 6 - Cleanup': cleanup.md 
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
     text: 'Roboto'
     code: 'Consolas'
  feature:
    tabs: true
# Customizations
markdown_extensions:
  - admonition
  - codehilite   
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
